MapColonies/discrete-overseer-creator

- .eslintrc.json
- package-lock.json
- package.json
- src/common/controllers/openapi.ts
- src/common/routes/openapi.ts
- src/serverBuilder.ts
- tests/integration/resourceName/resourceName.spec.ts
| New feature     | ✔                                                                     | …
> feat: added relative ref support to openapi

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- package.json
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/publisherClient.ts
- src/serviceClients/storageClient.ts
| New feature     | ✔                                                                     | …
> feat: added http clients skeletons

- openapi3.yaml
- src/progress/controllers/progressController.ts
- src/progress/interfaces.ts
- src/progress/models/progressManager.ts
- src/progress/routes/progressRouter.ts
- src/serverBuilder.ts
> feat: added progress controller skeleton

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- package.json
- src/common/middlewares/ErrorHandler.ts
- src/layers/controllers/layersController.ts
- src/layers/models/layersManager.ts
- src/serverBuilder.ts
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/clientsBase/kafkaClient.ts
- src/serviceClients/publisherClient.ts
- src/serviceClients/storageClient.ts
- src/serviceClients/tillerClient.ts
- tests/integration/Mocks.ts
- tests/integration/layers/helpers/requestSender.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/testContainerConfig.ts
- tests/unit/layers/models/layersModel.spec.ts
> feat: added basic create layer logic

- src/layers/models/layersManager.ts
- tests/integration/layers/layers.spec.ts
| Tests added     | ✔                                                                     | …
> test: added tests for external errors

- src/progress/controllers/progressController.ts
- src/progress/interfaces.ts
- src/progress/models/progressManager.ts
- src/serviceClients/publisherClient.ts
- src/serviceClients/storageClient.ts
- tests/integration/Mocks.ts
- tests/integration/progress/helpers/requestSender.ts
- tests/integration/progress/progress.spec.ts
- tests/integration/testContainerConfig.ts
- tests/unit/layers/models/progressModel.spec.ts
> feat: added task completion logic

- .prettierrc.json
- openapi3.yaml
- package-lock.json
- package.json
- src/layers/controllers/layersController.ts
- src/layers/models/layersManager.ts
- src/serviceClients/storageClient.ts
- tests/integration/layers/helpers/requestSender.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/layers/models/layersModel.spec.ts
| Breaking change | ✔                                                                        | …
> feat: update models

- src/layers/models/layersManager.ts
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/publisherClient.ts
- src/serviceClients/storageClient.ts
- src/tasks/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/integration/Mocks.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/tasks/tasks.spec.ts
- tests/integration/testContainerConfig.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: db integration

- src/layers/interfaces.ts
- src/serviceClients/mapPublisherClient.ts
- src/tasks/models/tasksManager.ts
- tests/integration/Mocks.ts
- tests/integration/testContainerConfig.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: map proxy api integration

- src/layers/interfaces.ts
- src/serviceClients/mapPublisherClient.ts
- src/tasks/models/tasksManager.ts
- tests/unit/tasks/models/tasksModel.spec.ts
| Bug fix         | ✔                                                            | …
> fix: map proxy api integration

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- package.json
- src/serviceClients/catalogClient.ts
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/clientsBase/kafkaClient.ts
- src/serviceClients/mapPublisherClient.ts
- src/serviceClients/storageClient.ts
> feat: add retries for external services calls

- Dockerfile
- openapi3.yaml
- package-lock.json
- package.json
- src/common/enums.ts
- src/layers/models/layersManager.ts
- src/serviceClients/catalogClient.ts
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/storageClient.ts
- src/tasks/controllers/tasksController.ts
- src/tasks/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/tasks/helpers/requestSender.ts
- tests/integration/tasks/tasks.spec.ts
- tests/mocks/clients/storageClient.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
| Breaking change | ✔                                                                        | …
> Db integration

- Dockerfile
> fix: fixed openshift premissions in dockerfile

- Dockerfile
> fix: fixed usr premissions

- .dockerignore
- config/custom-environment-variables.json
- config/default.json
- openapi3.yaml
- package-lock.json
- package.json
- src/layers/controllers/layersController.ts
- src/layers/models/fileValidator.ts
- src/layers/models/layersManager.ts
- src/serviceClients/clientsBase/httpClient.ts
- src/serviceClients/clientsBase/kafkaClient.ts
- src/serviceClients/storageClient.ts
- src/tasks/models/tasksManager.ts
- src/tasks/routes/tasksRouter.ts
- tests/integration/layers/helpers/requestSender.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/layers/models/layersModel.spec.ts
| Breaking change | ✔                                                                        |
| Deprecations    | ✔                                                                        |
| Documentation   | ✔                                                                        | …
> Source dir

- config/custom-environment-variables.json
- config/default.json
- src/serviceClients/clientsBase/kafkaClient.ts
> chore(configurations): add ssl option

- .github/workflows/release-on-tag-push.yaml
- .redocly.yaml
- openapi3.yaml
- package-lock.json
- package.json
- src/layers/models/layersManager.ts
- src/serviceClients/storageClient.ts
- src/tasks/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/integration/layers/layers.spec.ts
- tests/mocks/clients/storageClient.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: updated model to v7

- config/default.json
- config/linkTemplates.template
- package-lock.json
- package.json
- src/serverBuilder.ts
- src/serviceClients/catalogClient.ts
- src/tasks/models/linksBuilder.ts
- src/tasks/models/tasksManager.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/tasks/tasks.spec.ts
- tests/mocks/clients/catalogClient.ts
- tests/mocks/linkBuilder.ts
- tests/unit/tasks/models/linkBuilder.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
| Breaking change | /✖                                                                        | …
> feat: catalog integration

- .gitignore
- config/default.json
- package-lock.json
- src/layers/models/layersManager.ts
- src/tasks/models/tasksManager.ts
- src/toc/models/tocManager.ts
- src/utils/zoomToResulation.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
- tests/unit/utils/zoomToResulation.spec.ts
> feat: add resolution to zoom level

- package-lock.json
- package.json
> fix: geojson bbox validation

- config/custom-environment-variables.json
- config/default.json
- src/tasks/models/tasksManager.ts
> fix: splited config for public map server url

- src/layers/models/layersManager.ts
- src/serviceClients/clientsBase/httpClient.ts
> chore: improved logs

- config/custom-environment-variables.json
- config/default.json
- src/common/enums.ts
- src/layers/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: send tiles location to mapProxyAPI

- config/custom-environment-variables.json
- config/linkTemplates.template
| Bug fix         | ✔/                                                                       | …
> fix: link template path config and defaults

- src/serviceClients/storageClient.ts
> feat: set job initial status to in-progress instead of pending

- src/layers/models/layersManager.ts
- src/tasks/models/tasksManager.ts
- src/utils/zoomToResulation.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
- tests/unit/utils/zoomToResulation.spec.ts
> feat: fix resolution tasks creation bug

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- src/serviceClients/syncClient.ts
- src/tasks/models/tasksManager.ts
- tests/mocks/clients/syncClient.ts
- tests/unit/tasks/models/tasksModel.spec.ts
Trigger sync process from overseer
> feat: add sync triggering from overseer

- openapi3.yaml
- src/serviceClients/catalogClient.ts
- src/serviceClients/syncClient.ts
- src/tasks/models/tasksManager.ts
- src/toc/interfaces.ts
- src/toc/models/tocManager.ts
- tests/integration/toc/helpers/data.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: update sync and ToC API

- src/layers/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> fix: removed unnecessary desc field

- config/custom-environment-variables.json
- config/default.json
- src/serverBuilder.ts
> feat: added payload limit configuration

- src/layers/models/layersManager.ts
- tests/integration/layers/helpers/requestSender.ts
- tests/integration/layers/layers.spec.ts
> fix: prevent getting id in swagger

- src/toc/models/tocManager.ts
> chore: fix error log

- src/layers/models/layersManager.ts
- src/serviceClients/catalogClient.ts
- src/serviceClients/jobManagerClient.ts
- src/tasks/models/tasksManager.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/tasks/tasks.spec.ts
- tests/integration/testContainerConfig.ts
- tests/integration/toc/layers.spec.ts
- tests/mocks/clients/jobManagerClient.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: updated to new jpb manager api

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- package.json
- src/layers/interfaces.ts
- src/layers/models/layersManager.ts
- src/layers/models/tasker.ts
- src/serviceClients/jobManagerClient.ts
- tests/integration/testContainerConfig.ts
- tests/mocks/clients/jobManagerClient.ts
- tests/mocks/tasker.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/layers/models/tasker.spec.ts
> feat: added task bboxs

- package-lock.json
- src/layers/models/layersManager.ts
- src/update/metadataMerger.ts
- src/utils/bbox.ts
- tests/unit/update/metadataMerger.spec.ts
> feat: added metadata merger

- package-lock.json
- package.json
- src/tasks/models/tasksManager.ts
> chore: updated mc-models version

- config/custom-environment-variables.json
- config/default.json
- package-lock.json
- src/layers/models/layersManager.ts
- src/layers/models/tasker.ts
- src/serviceClients/jobManagerClient.ts
- src/tasks/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/layers/models/tasker.spec.ts
> fix: hot fix - batched tasks creation

- src/layers/models/layersManager.ts
- src/serviceClients/catalogClient.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/layers/models/tasker.spec.ts
> fix: validation fix for exists in catalog

- config/default.json
- package-lock.json
- tests/configurations/integration/jest.config.js
- tests/configurations/unit/jest.config.js
- tests/integration/layers/layers.spec.ts
- tests/integration/toc/toc.spec.ts
- tests/mocks/clients/jobManagerClient.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
| Documentation   |/✖                                                                        | …
> chore: updated Tests for tasks batching

- src/layers/interfaces.ts
- src/layers/models/tasker.ts
- tests/unit/layers/models/tasker.spec.ts
| Breaking change | ✔                                                                        |
| Deprecations    | ✔                                                                        | …
> feat!: removed file names from tasks

- CHANGELOG.md
- package-lock.json
- package.json
- src/layers/models/layersManager.ts
- src/serviceClients/jobManagerClient.ts
- src/tasks/models/tasksManager.ts
- src/utils/layerNameGenerator.ts
- src/utils/zoomToResolution.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/layers/models/layersModel.spec.ts
- tests/unit/layers/models/tasker.spec.ts
- tests/unit/tasks/models/tasksModel.spec.ts
- tests/unit/utils/layerNameGenerator.spec.ts
- tests/unit/utils/zoomToResulation.spec.ts
> chore: removed OrthophotoHistory unique logic

- src/common/enums.ts
- src/tasks/models/tasksManager.ts
> fix: updating job status on after abort/expire

- helm/templates/configmap.yaml
- helm/values.yaml
> chore: adapt config provider key

- src/common/interfaces.ts
- src/layers/models/fileValidator.ts
- src/layers/models/layersManager.ts
- src/merge/mergeTilesTasker.ts
- tests/integration/layers/layers.spec.ts
- tests/unit/merger/mergeTilesTasker.spec.ts
> fix: merge api

- helm/templates/configmap.yaml
- helm/values.yaml
> fix: job-management configuration

- helm/config/linkTemplates.template
- helm/templates/configmap.yaml
- helm/values.yaml
> feat: allowed removing wms from links

- package-lock.json
- package.json
- src/common/utills/polygonPartsBuilder.ts
- src/update/metadataMerger.ts
- tests/integration/layers/layers.spec.ts
- tests/integration/toc/helpers/data.ts
- tests/unit/layers/models/layersManager.spec.ts
- tests/unit/layers/models/splitTilesTasker.spec.ts
- tests/unit/update/metadataMerger.spec.ts
| Breaking change | ✔                                                                      |
| Chore            | ✔ …
> fix: remove unused updateDate param

- config/default.json
> fix: remove unused map config

- src/layers/models/fileValidator.ts
> fix: gpkg extension is now valid in all captilization cases

- package-lock.json
- package.json
> fix: merge tasks bounds

- src/serviceClients/sqliteClient.ts
> feat: constraint index validation support

- src/serviceClients/jobManagerClient.ts
- src/tasks/interfaces.ts
- src/tasks/models/tasksManager.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> feat: added job percentage support

- package-lock.json
- package.json
| Bug fix         | ✔                                                                      |
| Chore            | ✔ …
> chore: bumping @map-colonies/storage-explorer-middleware 1.2.5

- package-lock.json
- package.json
> chore: update file explorer and bump

- config/linkTemplates.template
- helm/config/linkTemplates.template
- helm/values.yaml
- tests/unit/tasks/models/linkBuilder.spec.ts
> feat: add base wms and wmts links

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- Dockerfile
- package-lock.json
- src/tasks/models/tasksManager.ts
- tests/unit/tasks/models/tasksModel.spec.ts
> fix: job status update logic

- src/layers/models/layersManager.ts
- tests/integration/layers/layers.spec.ts
| Bug fix         | ✔                                                                      | …
> fix: error code on not valid layer version

- src/common/enums.ts
- src/common/interfaces.ts
- src/merge/mergeTilesTasker.ts
- src/serviceClients/jobManagerClient.ts
- tests/unit/merger/mergeTilesTasker.spec.ts
> fix: add targetFormat-jpeg

- src/common/interfaces.ts
- src/layers/models/layersManager.ts
- src/merge/mergeTilesTasker.ts
- src/serviceClients/jobManagerClient.ts
- tests/unit/layers/models/layersManager.spec.ts
- tests/unit/merger/mergeTilesTasker.spec.ts
> chore: added isNew task parameter for new source

- package-lock.json
- src/layers/models/layersManager.ts
- tests/integration/layers/layers.spec.ts
> fix: fix decimal version bug (MAPCO-2765)

- openapi3.yaml
- package-lock.json
- package.json
| Bug fix         | ✔                                                                       |
| Chore            | ✔ …
> chore: update mc-models version to support product_type from the package
